# Introduction to practical sessions

We will use jupyter notebooks for the practical sessions. Each group will use a dedicated GPU with corresponding jupyter kernel on the thalassa cluster. In order to use it, each group will connect to their kernel via firefox.

<img src="graphics/archi.png">



Introduction 
============

Practical sessions tools

-   Jupyter notebook: A web application allowing to run code in a
    user-friendly environment
-   Python: a high level interpreted language

-   Numpy: a scientific computing libray

-   Keras: a high level deep learning library

    

# Jupyter notebok

This is a jupyter notebook. Each rectangle containing text or images is a "cell". Cells may contain non-executable text (markdown cells) or python code.

Active cells have a green left margin. Their contents can be modified or executed. A cell becomes "active" by simply clicking on it.

If "Escape" is pressed in an active cell, its state becomes "selected", and is marked by a blue left margin. A selected cell can executed, as an active cell, but also moved or erased.

Convenient shorcuts for executing cells are:

- Control-Enter : the cell is executed, and afterwards its state is "selected".

- Shift-Enter: the cell is executed, and the following cell becomes "selected".

Python in 5 minutes
===================

Python:

-   High-level language

-   Object-oriented with dynamic typing

-   Easy to interface with C++

-   Easy to learn (?)

We will use Python 3

Expressions, variables and types
--------------------------------

### Expressions

Examples of expressions:

In [3]:
2

2

In [4]:
2+2

4

In [5]:
"Hello"

'Hello'

In [6]:
# This is a comment

In [7]:
# print() is an example of function. It is a built-in function, always available in Python.
print("Hello")

Hello


### Variables

Variables are not declared:

In [8]:
a=2

In [9]:
print(a)

2


In [10]:
type(a)

int

In [11]:
b = 0.9
type(b)

float

In [12]:
print(a, b)

2 0.9


### Compound types: tuples and lists

Tuples

In [13]:
t1 = (1, "zz")
type(t1)

tuple

In [14]:
print(t1, t1[0], t1[1])

(1, 'zz') 1 zz


In [15]:
a, b = t1
print(a, b)

1 zz


Tuples are inmutable. Once they are created, the can only be
erased. They cannot be modified.

Lists

In [16]:
l1 = ["abc"]
l1.append(3.14159)  # List can be heterogeneous
l1

['abc', 3.14159]

### Indexing

Indexing of lists, tuples or other iterable types starts at 0. It their length is L, then the index of the last element is L-1.


In [17]:
print(l1[1])

3.14159


Lists are mutable. New elements can be added; existing
elements can be modified of deleted.

In [18]:
l1[1] = 0
print(l1[1])

0


# Functions

### Functions (1)

Declaring a function

In [19]:
def f(a):  # note the colon
    return 2*a   # note the indentation

print(f(3))

6


Indentation is *critical*: it’s part of the syntax.


### Functions (2)

Return value

In [20]:
def theAddition(a, b):
    return a + b

c = theAddition(1, 2)
print(c)

3


# Classes

A class in Python (as in many other object-oriented languages) is a
container that can hold:

-   Attributes (internal variables) and

-   Methods (internal functions).

A class is defined using the *class* keyword.

Example:

In [21]:
class Bird:
    def set_name(self, given_name):  # this is a class method
        self.name = given_name  # self represents the class instance. self.name is an instance attribute.

### Class instance

The execution of the above code creates a class. It can be instantiated
by calling it as a function:

In [22]:
robin = Bird()
robin.set_name("European robin")
print(robin.name)

European robin


The result is an object or instance built according to the class model.
The keyword *self* represents the class instance.

Instance attributes should in fact be initialized in a special method,
that is called when the class is instantiated:

In [23]:
class Bird:
    def __init__(self, given_name):
        self.name = given_name
        
robin = Bird("European robin")
print(robin.name)

European robin


Loops and tests
---------------

### Tests

Tests and conditions

In [24]:
if robin.name == "European robin":
    print("The bird is an European robin")
else:
    print("No")
            

The bird is an European robin


### Loops (1)

Simple loops

In [25]:
for i in range(5):
    print(i)

0
1
2
3
4


### Loops (2)

To loop over the items in a list:

In [26]:
for x in l1:
    print(x)

abc
0


### Loops (3)

“while” loops 

Infinite “while” loop:

In [28]:
a = 0
while True:
    a += 1
    if a == 10:
        print("This is the end!")
        break

This is the end!


“while” loop with a test:

In [29]:
while a < 20:
    a += 1
print("Now a is equal to: ", a)

Now a is equal to:  20


# Packages


A Python package is a module that brings new functions and classes when
*imported*.

The Python ecosystem offers thousands of packages.

### Importing packages

In [34]:
import numpy
b = numpy.cos(0)
print(b)

1.0


You can also use a short name for the package:

In [33]:
import numpy as np
np.cos(0)

1.0

# Numpy


-   A python module for scientific computing

-   Based on a powerful multi-dimensional array object

-   Efficient core coded in C++

## Numpy Arrays

Vectors, matrices and tensors can be represented with numpy arrays.

In [36]:
import numpy as np
a = np.array([2, 0, 3])
print(a)

[2 0 3]


In [37]:
type(a)

numpy.ndarray

In [39]:
a.dtype  # type of data stored in the array

dtype('int64')

In [40]:
a.ndim  # number of dimensions

1

In [41]:
a.shape 

(3,)

## 2D arrays

In [42]:
b = np.array([[2, 0, 4], [1, 3, 3]])
print(b)

[[2 0 4]
 [1 3 3]]


In [43]:
b.ndim

2

In [44]:
b.shape

(2, 3)

In [45]:
b[1, 0]

1

## Vector and matrix operations

By default, standard operators like \*, -, + , / , are applied
element-wise to arrays and vectors.

In [48]:
a = np.array([3, 0, 2])
b = np.array([[1, 2, 3], [0, 1, 0]])
print(a*b)

[[3 0 6]
 [0 0 0]]


In [49]:
print(b*b)

[[1 4 9]
 [0 1 0]]


In [50]:
print(b * b.transpose())

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [52]:
print(np.matmul(b,a))


[9 0]


In [53]:
np.matmul(b,b.transpose())

array([[14,  2],
       [ 2,  1]])

## Choosing elements within an array

In [54]:
b[1,1]

1

In [55]:
b[1,:]

array([0, 1, 0])

In [ ]:
b[:,1]

`      >>> b = np.array([1, 2, 3], [0, 1, 0])`\
\
`      >>> b[1,1]`\
\
`      1`\
\
`      >>> b[1,:]`\
\
`      array([0, 1, 0])`\
\
`      >>> b[:,1]`\
\
`      array([2, 1])`\
\
`      >>> b[:,0:2]`\
\
`      array([[1, 2],`\
`        [0, 1]]`\
\
`    `

Jupyter notebook
================

Conclusion
==========

### The end

Good Luck !